#
# Module manifest for module 'PSAwtrix3'
#
# Generated by: Frank Lindenblatt (Flittermelint)
#
# Generated on: 2024-03-25
#
@{
    RootModule        = 'PSAwtrix3.psm1'

    ModuleVersion     = '0.0.0'

    GUID              = '9cf46089-a134-41fb-8de6-c653aaf3b2e3'

    Author            = 'Frank Lindenblatt (Flittermelint)'

    Copyright         = 'Copyright (c) 2024 Frank Lindenblatt (Flittermelint), licensed under the MIT License.'

    Description       = 'Control the power of Ulanzi TC001 Smart Pixel clock and similar self build matrix clocks with powershell'

    PowerShellVersion = '5.1'

    PrivateData = @{

        PSData = @{

            Tags       = @('powershell', 'awtrix', 'matrix', 'pixel', 'clock', 'iot', 'smarthome', 'ulanzi')

            ProjectUri = 'https://github.com/Flittermelint/PSAwtrix3'

            LicenseUri = 'https://github.com/Flittermelint/PSAwtrix3/raw/main/LICENSE'

            IconUri    = 'https://github.com/Flittermelint/PSAwtrix3/raw/main/Images/PSAwtrix.Logo.png'
        }
    }
}
